theme: jekyll-theme-cayman
title: "Commons-IP"
description: "Command-line tool and Java library to create and validate Information Packages of different formats: E-ARK, BagIt, Hungarian type 4 SIP."
show_downloads: true
google_analytics: UA-101512240-1
