name: Release
on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Chache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build Jar
        run: mvn --batch-mode clean package -P cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Jar
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/}
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ steps.tag.outputs.VERSION }}
          tag_name: ${{ steps.tag.outputs.VERSION }}
          draft: true
          files: target/commons-ip2-cli-${{ steps.tag.outputs.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
