name: Release
on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Chache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set POM Version
        run: mvn versions:set versions:commit -DnewVersion=${{ github.ref }}
      - name: Build Jar
        run: mvn --batch-mode clean package -P cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Jar
        run:  mvn --batch-mode deploy -Djacoco.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: true
          files: target/commons-ip2-cli-${{ github.ref }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
